// Auto-generated by scripts/download-icons8.js
// Run `npm run download-icons` to populate this file with bundled icons8 3D-fluency icons.
// Icons by icons8 - https://icons8.com/license

export const PRODUCT_ICONS = {};
