#!/usr/bin/env node
/**
 * Downloads icons8 3D-fluency food/grocery icons and bundles them as base64 in product-icons.js.
 *
 * Usage: npm run download-icons
 *
 * IMPORTANT: icons8 free tier requires attribution.
 * See https://icons8.com/license for details.
 */

import https from 'https';
import fs from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Extract unique slugs from product-icon-map.js source
const iconMapPath = path.join(__dirname, '../src/icons/product-icon-map.js');
const iconMapSrc = fs.readFileSync(iconMapPath, 'utf8');
const slugSet = new Set();
for (const m of iconMapSrc.matchAll(/:\s*'([a-z0-9-]+)'/g)) slugSet.add(m[1]);

const slugs = [...slugSet];
console.log(`\nDownloading ${slugs.length} icons from icons8 3D-fluency...\n`);

function download(url) {
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      if (res.statusCode === 301 || res.statusCode === 302) {
        return download(res.headers.location).then(resolve).catch(reject);
      }
      if (res.statusCode !== 200) {
        reject(new Error(`HTTP ${res.statusCode}`));
        return;
      }
      const chunks = [];
      res.on('data', chunk => chunks.push(chunk));
      res.on('end', () => resolve(Buffer.concat(chunks)));
      res.on('error', reject);
    }).on('error', reject);
  });
}

const results = {};
let success = 0, fail = 0;

for (const slug of slugs) {
  const url = `https://img.icons8.com/3d-fluency/94/${slug}.png`;
  try {
    const buf = await download(url);
    // Verify PNG magic bytes
    if (buf[0] === 0x89 && buf[1] === 0x50) {
      results[slug] = `data:image/png;base64,${buf.toString('base64')}`;
      process.stdout.write(`  ✓ ${slug}\n`);
      success++;
    } else {
      process.stdout.write(`  ✗ ${slug} (not a valid PNG)\n`);
      fail++;
    }
  } catch (err) {
    process.stdout.write(`  ✗ ${slug} (${err.message})\n`);
    fail++;
  }
  // Small delay to be polite to the CDN
  await new Promise(r => setTimeout(r, 120));
}

const outPath = path.join(__dirname, '../src/icons/product-icons.js');
const content = `// Auto-generated by scripts/download-icons8.js — do not edit manually.
// Run \`npm run download-icons\` to refresh.
// Icons by icons8 - https://icons8.com/license
// Attribution required for free tier use.

export const PRODUCT_ICONS = ${JSON.stringify(results, null, 2)};
`;

fs.writeFileSync(outPath, content, 'utf8');

const sizeKb = Math.round(Buffer.byteLength(content, 'utf8') / 1024);
console.log(`\n✅ Done — ${success} icons bundled, ${fail} failed.`);
console.log(`📦 Output: src/icons/product-icons.js (${sizeKb} KB)`);
console.log('\n⚠️  Attribution required: "Icons by icons8 - https://icons8.com"\n');
console.log('Run `npm run build` to include the icons in the card bundle.\n');
