const TRANSLATIONS = {
  en: {
    'common.add': 'Add',
    'common.cancel': 'Cancel',
    'common.create': 'Create',
    'common.delete': 'Delete',
    'common.done': 'Done',
    'common.duplicate': 'Duplicate',
    'common.loading': 'Loading...',
    'common.loading_short': 'Loading...',
    'common.rename': 'Rename',
    'common.save': 'Save',
    'common.searching': 'Searching...',
    'common.working': 'Working...',

    'nav.shopping': 'Shopping',
    'nav.lists': 'Lists',
    'nav.loyalty': 'Loyalty',
    'nav.settings': 'Settings',

    'shopping.default_list': 'Shopping List',
    'shopping.empty': 'Your shopping list is empty',
    'shopping.empty_hint': 'Search for products to add items',
    'shopping.items': '{count} items',
    'shopping.recently_used': 'Recently Used',
    'shopping.unknown_view': 'Unknown view',

    'header.view': 'View',
    'header.tiles': 'Tiles',
    'header.list': 'List',
    'header.sort': 'Sort',
    'header.by_category': 'By Category',
    'header.alphabetical': 'A-Z',
    'header.show_price': 'Show Price',

    'search.placeholder': 'Search or add products...',
    'search.add_query': 'Add "{query}"',
    'search.quick_add': 'quick add to list',
    'search.create_product': 'Create product "{query}"',
    'search.create_product_subtitle': 'save to catalog with category & price',
    'search.create_new_product': 'Create new product',
    'search.matching_products': 'Matching products',
    'search.product_name': 'Product name',
    'search.price_optional': 'Price (optional)',
    'search.barcode_optional': 'Barcode (optional)',
    'search.create_and_add': 'Create & Add',
    'search.scan_barcode': 'Scan barcode',
    'search.oft_lookup': 'Looking up on OpenFoodFacts...',

    'scanner.product_barcode': 'Point camera at product barcode',
    'scanner.barcode': 'Point camera at barcode',
    'scanner.take_photo': 'Take a photo of the barcode',
    'scanner.live_unavailable': 'Live camera unavailable (HTTP). Use the button below to photograph the barcode.',
    'scanner.open_camera': 'Open Camera',
    'scanner.flip_camera': 'Flip Camera',
    'scanner.scanning': 'Scanning...',
    'scanner.not_found': 'No barcode found - try again with a clearer photo.',

    'dialog.add_item': 'Add Item',
    'dialog.search_products': 'Search products...',
    'dialog.add_custom_item': 'Add custom item...',
    'dialog.or': 'OR',
    'dialog.total': 'Total:',
    'dialog.add_to_list': 'Add to List',

    'edit.title': 'Edit Item',
    'edit.product_name': 'Product Name',
    'edit.search_oft_name': 'Search OFT by name',
    'edit.no_oft_results': 'No results found on OpenFoodFacts.',
    'edit.oft_results': '{count} result{plural} found - tap one to apply',
    'edit.oft_lookup_failed': 'OpenFoodFacts lookup failed.',
    'edit.local_barcode_found': 'Found in local catalog: "{name}"',
    'edit.barcode_not_found': 'Barcode not found on OpenFoodFacts.',
    'edit.oft_found': 'Found on OpenFoodFacts - tap to apply',
    'edit.updated_from_oft': 'Updated from OpenFoodFacts',
    'edit.barcode': 'Barcode',
    'edit.barcode_placeholder': 'Barcode number (optional)',
    'edit.search_oft_barcode': 'Search OpenFoodFacts by barcode',
    'edit.category': 'Category',
    'edit.quantity': 'Quantity',
    'edit.unit': 'Unit',
    'edit.other': 'Other...',
    'edit.custom_unit_placeholder': 'e.g. jar, punnet...',
    'edit.unit_price': 'Unit Price ($)',
    'edit.notes': 'Notes',
    'edit.notes_placeholder': 'Add notes (optional)...',
    'edit.product_image': 'Product Image',
    'edit.remove_image': 'Remove image',
    'edit.image_url_placeholder': 'Paste image URL...',
    'edit.browse_local_file': 'Browse local file',
    'edit.confirm_delete': 'Delete {name}?',
    'edit.dismiss': 'Dismiss',

    'lists.title': 'My Lists',
    'lists.new': 'New List',
    'lists.empty': 'No lists yet',
    'lists.empty_hint': 'Create your first shopping list',
    'lists.create': 'Create List',
    'lists.create_new': 'Create New List',
    'lists.name': 'List Name',
    'lists.name_placeholder': 'e.g., Weekly Shopping',
    'lists.icon': 'Icon',
    'lists.private': 'Private - only visible to me (and members I add)',
    'lists.active': 'Active',
    'lists.manage_members': 'Manage Members',
    'lists.members_hint': 'Select who else can see and edit this list.',
    'lists.loading_users': 'Loading users...',
    'lists.no_users': 'No other users found.',
    'lists.rename_prompt': 'Enter new list name:',
    'lists.delete_confirm': 'Delete this list?',
    'lists.copy_soon': 'Copy feature coming soon!',
    'lists.copy': 'Copy',

    'loyalty.title': 'Loyalty Cards',
    'loyalty.add_card': 'Add card',
    'loyalty.view_options': 'View options',
    'loyalty.empty': 'No loyalty cards yet',
    'loyalty.empty_hint': 'Add your store loyalty cards for quick access',
    'loyalty.card_view': 'Card View',
    'loyalty.tile_view': 'Tile View',
    'loyalty.add_title': 'Add Loyalty Card',
    'loyalty.edit_title': 'Edit Card',
    'loyalty.store_name': 'Store Name',
    'loyalty.store_placeholder': 'e.g., Countdown',
    'loyalty.card_number': 'Card Number',
    'loyalty.card_number_placeholder': 'Card/Member number',
    'loyalty.code_value': 'Code Value',
    'loyalty.code_placeholder': 'Auto-generated from number',
    'loyalty.code_type': 'Code Type',
    'loyalty.barcode': 'Barcode',
    'loyalty.qrcode': 'QR Code',
    'loyalty.logo_url': 'Shop Logo URL (optional)',
    'loyalty.notes': 'Notes',
    'loyalty.notes_placeholder': 'Additional notes...',
    'loyalty.card_color': 'Card Color',
    'loyalty.private': 'Private (only visible to you)',
    'loyalty.members': 'Members',
    'loyalty.members_hint': 'Select which users can see "{name}"',
    'loyalty.delete_confirm': 'Delete this loyalty card?',
    'loyalty.copy_suffix': 'Copy',
    'loyalty.tap_close': 'Tap anywhere to close',

    'settings.title': 'Settings',
    'settings.profile': 'Profile',
    'settings.user': 'User',
    'settings.appearance': 'Appearance',
    'settings.appearance_subtitle': 'Theme, tiles, fonts',
    'settings.notifications': 'Notifications',
    'settings.notifications_subtitle': 'List sharing, emails',
    'settings.preferences': 'Preferences',
    'settings.open_last': 'Open last used list at launch',
    'settings.keep_screen_on': 'Keep screen turned on',
    'settings.lists': 'Lists',
    'settings.region_catalog': 'Region & Catalog',
    'settings.region_catalog_subtitle': 'Country-specific products and pricing',
    'settings.categories': 'Manage Categories',
    'settings.categories_count': '{count} categories',
    'settings.support': 'Support',
    'settings.faq_support': 'FAQ & Support',
    'settings.refresh': 'Refresh',
    'settings.app': 'App',
    'settings.integration_version': 'Integration version {version}',
    'settings.card_version': 'Card version {version}',

    'profile.name': 'Name',
    'profile.account': 'Home Assistant Account',
    'profile.administrator': 'Administrator',
    'profile.notice': 'Profile information is managed through Home Assistant settings.',

    'appearance.dark_mode': 'Dark Mode',
    'appearance.theme': 'Theme',
    'appearance.all_modes': 'All Modes',
    'appearance.light_themes': 'Light Themes',
    'appearance.dark_themes': 'Dark Themes',
    'appearance.display': 'Display',
    'appearance.use_emojis': 'Use Emojis Instead of Icons',
    'appearance.tiles_per_row': 'Tiles Per Row',
    'appearance.recent_products': 'Recently Used Products',
    'appearance.products': '{count} products',
    'appearance.product_images': 'Product Images',
    'appearance.local_image_path': 'Local HA Image Path',
    'appearance.local_image_hint': 'Auto-match images by product name slug',
    'appearance.font': 'Font',
    'appearance.use_system_text_size': 'Use system text size',
    'appearance.font_size': 'Font Size',
    'appearance.font_weight': 'Font Weight',
    'appearance.font_family': 'Font Family',
    'appearance.light': 'Light',
    'appearance.regular': 'Regular',
    'appearance.bold': 'Bold',
    'appearance.on': 'On',
    'appearance.off': 'Off',
    'appearance.system': 'As on Device',
    'appearance.system_default': 'System Default',

    'notifications.list_sharing': 'List Sharing',
    'notifications.list_sharing_desc': 'Get notified when somebody shares a list with you or makes changes on shared lists',
    'notifications.emails': 'E-Mails',
    'notifications.emails_desc': 'Get notified about changes to your shared lists',

    'categories.title': 'Manage Categories',
    'categories.add': 'Add Category',
    'categories.reorder': 'Reorder',
    'categories.name': 'Category Name',
    'categories.name_placeholder': 'e.g., Snacks',
    'categories.icon': 'Icon',
    'categories.color': 'Color',
    'categories.coming_soon': 'Category management coming soon!',

    'data.load_failed': 'Failed to load region settings.',
    'data.export_success': 'Exported {products} custom product{productPlural} and {lists} list{listPlural}',
    'data.export_failed': 'Export failed. Please try again.',
    'data.invalid_backup': 'Invalid backup file.',
    'data.import_success': 'Imported {products} product{productPlural}, {lists} list{listPlural}, {items} item{itemPlural}. Reload to see changes.',
    'data.import_failed': 'Import failed. Make sure the file is a valid backup.',
    'data.switch_confirm': 'Switch to {country}?\\n\\nDefault catalog products will be replaced with {country} products. Your custom products are kept.',
    'data.switch_success': 'Switched to {country} - {count} products loaded',
    'data.switch_failed': 'Failed to switch region. Please try again.',
    'data.catalog_region': 'Product Catalog Region',
    'data.region': 'Region',
    'data.switching': 'Switching catalog...',
    'data.about': 'About',
    'data.how_it_works': 'How it works',
    'data.how_it_works_desc': "Switching region replaces the default product catalog (names, prices, brands) with one suited to your country. Any products you've created or customised are preserved. The change takes effect immediately - no restart needed.",
    'data.backup_restore': 'Backup & Restore',
    'data.export_data': 'Export Data',
    'data.export_desc': 'Download your custom products and lists as a JSON file. Catalog products are excluded - they reload automatically.',
    'data.download_backup': 'Download backup',
    'data.import_data': 'Import Data',
    'data.import_desc': 'Restore from a backup file. Existing data is kept - only missing products and lists are added.',
    'data.choose_backup': 'Choose backup file',

    'support.faq': 'FAQ',
    'support.faq_desc': 'Frequently asked questions',
    'support.report': 'Report a Problem',
    'support.report_desc': 'Submit an issue on GitHub',
    'support.github': 'GitHub Repository',
    'support.github_desc': 'View source code',
  },

  nl: {
    'common.add': 'Toevoegen',
    'common.cancel': 'Annuleren',
    'common.create': 'Aanmaken',
    'common.delete': 'Verwijderen',
    'common.done': 'Klaar',
    'common.duplicate': 'Dupliceren',
    'common.loading': 'Laden...',
    'common.loading_short': 'Laden...',
    'common.rename': 'Hernoemen',
    'common.save': 'Opslaan',
    'common.searching': 'Zoeken...',
    'common.working': 'Bezig...',

    'nav.shopping': 'Boodschappen',
    'nav.lists': 'Lijsten',
    'nav.loyalty': 'Klantenkaarten',
    'nav.settings': 'Instellingen',

    'shopping.default_list': 'Boodschappenlijst',
    'shopping.empty': 'Je boodschappenlijst is leeg',
    'shopping.empty_hint': 'Zoek producten om items toe te voegen',
    'shopping.items': '{count} items',
    'shopping.recently_used': 'Recent gebruikt',
    'shopping.unknown_view': 'Onbekende weergave',

    'header.view': 'Weergave',
    'header.tiles': 'Tegels',
    'header.list': 'Lijst',
    'header.sort': 'Sorteren',
    'header.by_category': 'Op categorie',
    'header.alphabetical': 'A-Z',
    'header.show_price': 'Prijs tonen',

    'search.placeholder': 'Zoek of voeg producten toe...',
    'search.add_query': '"{query}" toevoegen',
    'search.quick_add': 'snel toevoegen aan lijst',
    'search.create_product': 'Product "{query}" aanmaken',
    'search.create_product_subtitle': 'opslaan in catalogus met categorie en prijs',
    'search.create_new_product': 'Nieuw product aanmaken',
    'search.matching_products': 'Gevonden producten',
    'search.product_name': 'Productnaam',
    'search.price_optional': 'Prijs (optioneel)',
    'search.barcode_optional': 'Barcode (optioneel)',
    'search.create_and_add': 'Aanmaken & toevoegen',
    'search.scan_barcode': 'Barcode scannen',
    'search.oft_lookup': 'Opzoeken op OpenFoodFacts...',

    'scanner.product_barcode': 'Richt de camera op de productbarcode',
    'scanner.barcode': 'Richt de camera op de barcode',
    'scanner.take_photo': 'Maak een foto van de barcode',
    'scanner.live_unavailable': 'Live camera niet beschikbaar (HTTP). Gebruik de knop hieronder om de barcode te fotograferen.',
    'scanner.open_camera': 'Camera openen',
    'scanner.flip_camera': 'Camera wisselen',
    'scanner.scanning': 'Scannen...',
    'scanner.not_found': 'Geen barcode gevonden - probeer opnieuw met een duidelijkere foto.',

    'dialog.add_item': 'Item toevoegen',
    'dialog.search_products': 'Producten zoeken...',
    'dialog.add_custom_item': 'Eigen item toevoegen...',
    'dialog.or': 'OF',
    'dialog.total': 'Totaal:',
    'dialog.add_to_list': 'Toevoegen aan lijst',

    'edit.title': 'Item bewerken',
    'edit.product_name': 'Productnaam',
    'edit.search_oft_name': 'OFT zoeken op naam',
    'edit.no_oft_results': 'Geen resultaten gevonden op OpenFoodFacts.',
    'edit.oft_results': '{count} resultaat{plural} gevonden - tik om toe te passen',
    'edit.oft_lookup_failed': 'OpenFoodFacts opzoeken mislukt.',
    'edit.local_barcode_found': 'Gevonden in lokale catalogus: "{name}"',
    'edit.barcode_not_found': 'Barcode niet gevonden op OpenFoodFacts.',
    'edit.oft_found': 'Gevonden op OpenFoodFacts - tik om toe te passen',
    'edit.updated_from_oft': 'Bijgewerkt via OpenFoodFacts',
    'edit.barcode': 'Barcode',
    'edit.barcode_placeholder': 'Barcodenummer (optioneel)',
    'edit.search_oft_barcode': 'OpenFoodFacts zoeken op barcode',
    'edit.category': 'Categorie',
    'edit.quantity': 'Aantal',
    'edit.unit': 'Eenheid',
    'edit.other': 'Anders...',
    'edit.custom_unit_placeholder': 'bv. pot, bakje...',
    'edit.unit_price': 'Eenheidsprijs (€)',
    'edit.notes': 'Notities',
    'edit.notes_placeholder': 'Notities toevoegen (optioneel)...',
    'edit.product_image': 'Productafbeelding',
    'edit.remove_image': 'Afbeelding verwijderen',
    'edit.image_url_placeholder': 'Afbeeldings-URL plakken...',
    'edit.browse_local_file': 'Lokaal bestand kiezen',
    'edit.confirm_delete': '{name} verwijderen?',
    'edit.dismiss': 'Sluiten',

    'lists.title': 'Mijn lijsten',
    'lists.new': 'Nieuwe lijst',
    'lists.empty': 'Nog geen lijsten',
    'lists.empty_hint': 'Maak je eerste boodschappenlijst aan',
    'lists.create': 'Lijst aanmaken',
    'lists.create_new': 'Nieuwe lijst aanmaken',
    'lists.name': 'Lijstnaam',
    'lists.name_placeholder': 'bv. Weekboodschappen',
    'lists.icon': 'Icoon',
    'lists.private': 'Prive - alleen zichtbaar voor mij (en leden die ik toevoeg)',
    'lists.active': 'Actief',
    'lists.manage_members': 'Leden beheren',
    'lists.members_hint': 'Selecteer wie deze lijst ook kan zien en bewerken.',
    'lists.loading_users': 'Gebruikers laden...',
    'lists.no_users': 'Geen andere gebruikers gevonden.',
    'lists.rename_prompt': 'Nieuwe lijstnaam invoeren:',
    'lists.delete_confirm': 'Deze lijst verwijderen?',
    'lists.copy_soon': 'Kopieerfunctie komt binnenkort!',
    'lists.copy': 'Kopiëren',

    'loyalty.title': 'Klantenkaarten',
    'loyalty.add_card': 'Kaart toevoegen',
    'loyalty.view_options': 'Weergaveopties',
    'loyalty.empty': 'Nog geen klantenkaarten',
    'loyalty.empty_hint': 'Voeg je klantenkaarten toe voor snelle toegang',
    'loyalty.card_view': 'Kaartweergave',
    'loyalty.tile_view': 'Tegelweergave',
    'loyalty.add_title': 'Klantenkaart toevoegen',
    'loyalty.edit_title': 'Kaart bewerken',
    'loyalty.store_name': 'Winkelnaam',
    'loyalty.store_placeholder': 'bv. Delhaize',
    'loyalty.card_number': 'Kaartnummer',
    'loyalty.card_number_placeholder': 'Kaart-/lidnummer',
    'loyalty.code_value': 'Codewaarde',
    'loyalty.code_placeholder': 'Automatisch uit nummer',
    'loyalty.code_type': 'Codetype',
    'loyalty.barcode': 'Barcode',
    'loyalty.qrcode': 'QR-code',
    'loyalty.logo_url': 'Winkellogo-URL (optioneel)',
    'loyalty.notes': 'Notities',
    'loyalty.notes_placeholder': 'Extra notities...',
    'loyalty.card_color': 'Kaartkleur',
    'loyalty.private': 'Prive (alleen zichtbaar voor jou)',
    'loyalty.members': 'Leden',
    'loyalty.members_hint': 'Selecteer welke gebruikers "{name}" kunnen zien',
    'loyalty.delete_confirm': 'Deze klantenkaart verwijderen?',
    'loyalty.copy_suffix': 'Kopie',
    'loyalty.tap_close': 'Tik ergens om te sluiten',

    'settings.title': 'Instellingen',
    'settings.profile': 'Profiel',
    'settings.user': 'Gebruiker',
    'settings.appearance': 'Weergave',
    'settings.appearance_subtitle': 'Thema, tegels, lettertypes',
    'settings.notifications': 'Meldingen',
    'settings.notifications_subtitle': 'Lijsten delen, e-mails',
    'settings.preferences': 'Voorkeuren',
    'settings.open_last': 'Laatst gebruikte lijst openen bij starten',
    'settings.keep_screen_on': 'Scherm ingeschakeld houden',
    'settings.lists': 'Lijsten',
    'settings.region_catalog': 'Regio & catalogus',
    'settings.region_catalog_subtitle': 'Landsspecifieke producten en prijzen',
    'settings.categories': 'Categorieën beheren',
    'settings.categories_count': '{count} categorieën',
    'settings.support': 'Ondersteuning',
    'settings.faq_support': 'FAQ & ondersteuning',
    'settings.refresh': 'Vernieuwen',
    'settings.app': 'App',
    'settings.integration_version': 'Integratieversie {version}',
    'settings.card_version': 'Kaartversie {version}',

    'profile.name': 'Naam',
    'profile.account': 'Home Assistant-account',
    'profile.administrator': 'Beheerder',
    'profile.notice': 'Profielinformatie wordt beheerd via Home Assistant-instellingen.',

    'appearance.dark_mode': 'Donkere modus',
    'appearance.theme': 'Thema',
    'appearance.all_modes': 'Alle modi',
    'appearance.light_themes': 'Lichte thema\'s',
    'appearance.dark_themes': 'Donkere thema\'s',
    'appearance.display': 'Weergave',
    'appearance.use_emojis': 'Emoji\'s gebruiken in plaats van iconen',
    'appearance.tiles_per_row': 'Tegels per rij',
    'appearance.recent_products': 'Recent gebruikte producten',
    'appearance.products': '{count} producten',
    'appearance.product_images': 'Productafbeeldingen',
    'appearance.local_image_path': 'Lokaal HA-afbeeldingspad',
    'appearance.local_image_hint': 'Afbeeldingen automatisch koppelen via productnaam-slug',
    'appearance.font': 'Lettertype',
    'appearance.use_system_text_size': 'Tekstgrootte van systeem gebruiken',
    'appearance.font_size': 'Tekstgrootte',
    'appearance.font_weight': 'Letterdikte',
    'appearance.font_family': 'Lettertypefamilie',
    'appearance.light': 'Licht',
    'appearance.regular': 'Normaal',
    'appearance.bold': 'Vet',
    'appearance.on': 'Aan',
    'appearance.off': 'Uit',
    'appearance.system': 'Zoals op apparaat',
    'appearance.system_default': 'Systeemstandaard',

    'notifications.list_sharing': 'Lijsten delen',
    'notifications.list_sharing_desc': 'Krijg een melding wanneer iemand een lijst met je deelt of wijzigingen aanbrengt in gedeelde lijsten',
    'notifications.emails': 'E-mails',
    'notifications.emails_desc': 'Krijg meldingen over wijzigingen aan je gedeelde lijsten',

    'categories.title': 'Categorieën beheren',
    'categories.add': 'Categorie toevoegen',
    'categories.reorder': 'Herschikken',
    'categories.name': 'Categorienaam',
    'categories.name_placeholder': 'bv. Snacks',
    'categories.icon': 'Icoon',
    'categories.color': 'Kleur',
    'categories.coming_soon': 'Categoriebeheer komt binnenkort!',

    'data.load_failed': 'Regio-instellingen laden mislukt.',
    'data.export_success': '{products} eigen product{productPlural} en {lists} lijst{listPlural} geexporteerd',
    'data.export_failed': 'Exporteren mislukt. Probeer opnieuw.',
    'data.invalid_backup': 'Ongeldig back-upbestand.',
    'data.import_success': '{products} product{productPlural}, {lists} lijst{listPlural}, {items} item{itemPlural} geimporteerd. Herlaad om wijzigingen te zien.',
    'data.import_failed': 'Importeren mislukt. Controleer of het bestand een geldige back-up is.',
    'data.switch_confirm': 'Overschakelen naar {country}?\\n\\nStandaard catalogusproducten worden vervangen door producten voor {country}. Je eigen producten blijven bewaard.',
    'data.switch_success': 'Overgeschakeld naar {country} - {count} producten geladen',
    'data.switch_failed': 'Regio wijzigen mislukt. Probeer opnieuw.',
    'data.catalog_region': 'Productcatalogusregio',
    'data.region': 'Regio',
    'data.switching': 'Catalogus omschakelen...',
    'data.about': 'Over',
    'data.how_it_works': 'Hoe het werkt',
    'data.how_it_works_desc': 'Regio wijzigen vervangt de standaard productcatalogus (namen, prijzen, merken) door een versie voor jouw land. Producten die je zelf hebt aangemaakt of aangepast blijven bewaard. De wijziging gaat meteen in - geen herstart nodig.',
    'data.backup_restore': 'Back-up & herstellen',
    'data.export_data': 'Data exporteren',
    'data.export_desc': 'Download je eigen producten en lijsten als JSON-bestand. Catalogusproducten worden niet meegenomen - die laden automatisch opnieuw.',
    'data.download_backup': 'Back-up downloaden',
    'data.import_data': 'Data importeren',
    'data.import_desc': 'Herstel vanuit een back-upbestand. Bestaande data blijft bewaard - alleen ontbrekende producten en lijsten worden toegevoegd.',
    'data.choose_backup': 'Back-upbestand kiezen',

    'support.faq': 'FAQ',
    'support.faq_desc': 'Veelgestelde vragen',
    'support.report': 'Probleem melden',
    'support.report_desc': 'Een issue indienen op GitHub',
    'support.github': 'GitHub-repository',
    'support.github_desc': 'Broncode bekijken',
  },
};

function getLanguage(hass) {
  const language =
    hass?.locale?.language ||
    hass?.language ||
    hass?.selectedLanguage ||
    hass?.user?.language ||
    navigator.language ||
    'en';
  return String(language).toLowerCase().split('-')[0];
}

export function t(hass, key, vars = {}) {
  const language = getLanguage(hass);
  const value = TRANSLATIONS[language]?.[key] ?? TRANSLATIONS.en[key] ?? key;
  return Object.entries(vars).reduce(
    (text, [name, replacement]) => text.replaceAll(`{${name}}`, replacement ?? ''),
    value
  );
}

